spring.application.name=TrueReach

server.port=${PORT:8080}

#spring.mongodb.uri= ${MONGODB_URI}
spring.mongodb.uri= mongodb+srv://soumyajit:soumyajit@soumyajit.tnbjrqj.mongodb.net/TrueReach_DB

spring.data.mongodb.auto-index-creation=true
